baseurl: ""
url: "https://arulprakasht.github.io"

google_analytics_id: "{{ site.GOOGLE_ANALYTICS_ID }}"
microsoft_clarity_id: "{{ site.MICROSOFT_CLARITY_ID }}"
google_ads_client: "{{ site.GOOGLE_ADS_CLIENT }}"
linkedin_profile: "{{ site.LINKEDIN_PROFILE }}"

/* */
